### ISSUE TITLE
JSON specification disagreement

### ISSUE THREAD

**Issue by Gunisalvo** [jpereira/php-dhcpdleases#1]
Hey Jorge, I would like to suggest the following behaviour:

Right now we are getting the relay results in the following format:

{ status: "error", msg: "not found" }

But according to the specification:

http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf

Section 6 Objects:
"An object structure is represented as a pair of curly bracket tokens surrounding zero or more name/value pairs.
A name is a string. A single colon token follows each name, separating the name from the value. A single
comma token separates a value from a following name. "

Meaning that it should be:

{ "status" : "error", "msg" : "not found" }

So most frameworks will not inter-op with your library out of the box.

Thank you

**Comment by jpereira** [comment]
Hi @Gunisalvo ,

the issue was fixed, thanks!
